### ISSUE TITLE
Does AccProbe look at UI automation?

### ISSUE THREAD

**Issue by DavidMacDonald** [IBMa/AccProbe#8]
I see MSAA and iAccessible but no mention of UI Automation... thoughts?

**Comment by moekraft** [comment]
Hi Dave, 

AccProbe tests MSAA and IAccessible2 implementations. It does not examine or test UI Automation. Microsoft's Inspect can noew examine UI Automation, https://msdn.microsoft.com/en-us/library/windows/desktop/dd318521(v=vs.85).aspx.

Moe
